(* Generated by ocaml-tree-sitter. *)
(*
   pascal grammar

   entrypoint: root
*)

open! Sexplib.Conv
open Tree_sitter_run

type tok_prec_p5_pat_9f5699f = Token.t

type ktrue = Token.t (* pattern true *)

type kobjcprotocol = Token.t (* pattern objcprotocol *)

type kbegin = Token.t (* pattern begin *)

type kfalse = Token.t (* pattern false *)

type klabel = Token.t (* pattern label *)

type kset = Token.t (* pattern set *)

type kinterface = Token.t (* pattern interface *)

type kobject = Token.t (* pattern object *)

type kcdecl = Token.t (* pattern cdecl *)

type kuses = Token.t (* pattern uses *)

type imm_tok_pat_f57674d = Token.t (* pattern %[01]+ *)

type kdeprecated = Token.t (* pattern deprecated *)

type kinline = Token.t (* pattern inline *)

type kunimplemented = Token.t (* pattern unimplemented *)

type kvar = Token.t (* pattern var *)

type kinitialization = Token.t (* pattern initialization *)

type kiocheck = Token.t (* pattern iocheck *)

type kprocedure = Token.t (* pattern procedure *)

type koperator = Token.t (* pattern operator *)

type kgeneric = Token.t (* pattern generic *)

type ppendif = Token.t

type kthreadvar = Token.t (* pattern threadvar *)

type kconstructor = Token.t (* pattern constructor *)

type kexternal = Token.t (* pattern external *)

type pat_cdd9bad = Token.t (* pattern "'[^']*'" *)

type ksaveregisters = Token.t (* pattern saveregisters *)

type kpacked = Token.t (* pattern packed *)

type pat_cafba40 = Token.t (* pattern [0-9a-fA-F] *)

type kinherited = Token.t (* pattern inherited *)

type kshr = Token.t (* pattern shr *)

type kdownto = Token.t (* pattern downto *)

type kraiseat = Token.t

type krequired = Token.t (* pattern required *)

type kif = Token.t (* pattern if *)

type kwith = Token.t (* pattern with *)

type kconst = Token.t (* pattern const *)

type kexports = Token.t (* pattern exports *)

type knoreturn = Token.t (* pattern noreturn *)

type kmwpascal = Token.t (* pattern mwpascal *)

type kpackage = Token.t (* pattern package *)

type kfar = Token.t (* pattern far *)

type kobjcclass = Token.t (* pattern objcclass *)

type kexport = Token.t (* pattern export *)

type tok_prec_p5_pat_ef0cc7f = Token.t

type kdynamic = Token.t (* pattern dynamic *)

type krepeat = Token.t (* pattern repeat *)

type koptional = Token.t (* pattern optional *)

type klibrary = Token.t (* pattern library *)

type kvarargs = Token.t (* pattern varargs *)

type kshl = Token.t (* pattern shl *)

type kabstract = Token.t (* pattern abstract *)

type kexperimental = Token.t (* pattern experimental *)

type kof = Token.t (* pattern of *)

type kwriteonly = Token.t (* pattern writeonly *)

type kcontains = Token.t (* pattern contains *)

type kreference = Token.t (* pattern reference *)

type pat_3ea53fb = Token.t (* pattern [.,:;+\-*\[\]<>&%$@] *)

type knil = Token.t (* pattern nil *)

type kto = Token.t (* pattern to *)

type tok_prec_p5_pat_0a9b8cd = Token.t

type kfinally = Token.t (* pattern finally *)

type kindex = Token.t (* pattern index *)

type kimplements = Token.t (* pattern implements *)

type kinterrupt = Token.t (* pattern interrupt *)

type pat_588cb21 =
  Token.t (* pattern [-+]?[0-9]*\.?[0-9]+([eE][+-]?[0-9]+)? *)

type kor = Token.t (* pattern or *)

type kdestructor = Token.t (* pattern destructor *)

type ppelse = Token.t

type kunit = Token.t (* pattern unit *)

type kcase = Token.t (* pattern case *)

type kis = Token.t (* pattern is *)

type kprogram = Token.t (* pattern program *)

type kvirtual = Token.t (* pattern virtual *)

type knostackframe = Token.t (* pattern nostackframe *)

type kplatform = Token.t (* pattern platform *)

type kgoto = Token.t (* pattern goto *)

type kstdcall = Token.t (* pattern stdcall *)

type karray = Token.t (* pattern array *)

type kdo = Token.t (* pattern do *)

type kconstref = Token.t (* pattern constref *)

type kon = Token.t (* pattern on *)

type klocal = Token.t (* pattern local *)

type kwhile = Token.t (* pattern while *)

type kdefault = Token.t (* pattern default *)

type kpublished = Token.t (* pattern published *)

type kcvar = Token.t (* pattern cvar *)

type ksealed = Token.t (* pattern sealed *)

type kuntil = Token.t (* pattern until *)

type krequires = Token.t (* pattern requires *)

type kwrite = Token.t (* pattern write *)

type ppfragmentstmt = Token.t

type krecord = Token.t (* pattern record *)

type kpascal = Token.t (* pattern pascal *)

type kprivate = Token.t (* pattern private *)

type kms_abi_default = Token.t (* pattern ms_abi_default *)

type kout = Token.t (* pattern out *)

type identifier =
  Token.t (* pattern [&]?[\p{L}_][\p{L}\p{N}_$]*|\$[A-Z_][A-Z_0-9]*|\$\.\.\.[A-Z_][A-Z_0-9]* *)

type kreadonly = Token.t (* pattern readonly *)

type kraise = Token.t (* pattern raise *)

type kregister = Token.t (* pattern register *)

type kwinapi = Token.t (* pattern winapi *)

type kalias = Token.t (* pattern alias *)

type kdelayed = Token.t (* pattern delayed *)

type kreintroduce = Token.t (* pattern reintroduce *)

type kforward = Token.t (* pattern forward *)

type kmessage = Token.t (* pattern message *)

type koverload = Token.t (* pattern overload *)

type kcppdecl = Token.t (* pattern cppdecl *)

type kfinalization = Token.t (* pattern finalization *)

type kspecialize = Token.t (* pattern specialize *)

type ktry = Token.t (* pattern try *)

type kstatic = Token.t (* pattern static *)

type ksysv_abi_default = Token.t (* pattern sysv_abi_default *)

type kexcept = Token.t (* pattern except *)

type knodefault = Token.t (* pattern nodefault *)

type tok_prec_p5_pat_b66c674 = Token.t

type ksoftfloat = Token.t (* pattern softfloat *)

type kobjccategory = Token.t (* pattern objccategory *)

type koverride = Token.t (* pattern override *)

type kproperty = Token.t (* pattern property *)

type kelse = Token.t (* pattern else *)

type kstored = Token.t (* pattern stored *)

type pat_6c79139 =
  Token.t (* pattern "'''[ \\t]*\\r?\\n([^']|'[^']|''[^'])*'''" *)

type ppfragmentexpr = Token.t

type imm_tok_pat_d238afd = Token.t (* pattern \$[a-fA-F0-9]+ *)

type kclass = Token.t (* pattern class *)

type kprotected = Token.t (* pattern protected *)

type tok_prec_p5_pat_af36d87 = Token.t

type kdispinterface = Token.t (* pattern dispinterface *)

type kvectorcall = Token.t (* pattern vectorcall *)

type pat_f7c0026 = Token.t (* pattern \([^*]|\) *)

type knear = Token.t (* pattern near *)

type ktype = Token.t (* pattern type *)

type kimplementation = Token.t (* pattern implementation *)

type kresourcestring = Token.t (* pattern resourcestring *)

type ksafecall = Token.t (* pattern safecall *)

type kend = Token.t (* pattern end *)

type kin = Token.t (* pattern in *)

type kmod = Token.t (* pattern mod *)

type kdispid = Token.t (* pattern dispid *)

type khardfloat = Token.t (* pattern hardfloat *)

type kname = Token.t (* pattern name *)

type kstring = Token.t (* pattern string *)

type kas = Token.t (* pattern as *)

type khelper = Token.t (* pattern helper *)

type kpublic = Token.t (* pattern public *)

type kxor = Token.t (* pattern xor *)

type kms_abi_cdecl = Token.t (* pattern ms_abi_cdecl *)

type kasm = Token.t (* pattern asm *)

type ppif = Token.t

type kotherwise = Token.t (* pattern otherwise *)

type kread = Token.t (* pattern read *)

type ksysv_abi_cdecl = Token.t (* pattern sysv_abi_cdecl *)

type kand = Token.t (* pattern and *)

type kdiv = Token.t (* pattern div *)

type kfile = Token.t (* pattern file *)

type kfunction = Token.t (* pattern function *)

type kabsolute = Token.t (* pattern absolute *)

type kstrict = Token.t (* pattern strict *)

type tok_prec_p5_pat_6f93d17 = Token.t

type imm_tok_pat_ec19546 = Token.t (* pattern [-+]?[0-9]+ *)

type knot = Token.t (* pattern not *)

type kthen = Token.t (* pattern then *)

type kassembler = Token.t (* pattern assembler *)

type kfor = Token.t (* pattern for *)

type anon_choice_kto_86c5a40 = [
    `Kto of kto (*tok*)
  | `Kdow of kdownto (*tok*)
]

type literalfloat = pat_588cb21

type anon_choice_kstd_a801c0a = [
    `Kstd of kstdcall (*tok*)
  | `Kcdecl of kcdecl (*tok*)
  | `Ksaf of ksafecall (*tok*)
  | `Kreg of kregister (*tok*)
  | `Kpas of kpascal (*tok*)
  | `Kwin of kwinapi (*tok*)
]

type anon_choice_kname_ba8a152 = [
    `Kname of kname (*tok*)
  | `Kindex of kindex (*tok*)
]

type visibility = [
    `Kpub_1e1f5a9 of kpublished (*tok*)
  | `Kpub_659fa63 of kpublic (*tok*)
  | `Kpro of kprotected (*tok*)
  | `Kpri of kprivate (*tok*)
]

type anon_choice_kelse_d520062 = [
    `Kelse of kelse (*tok*)
  | `Koth of kotherwise (*tok*)
]

type anon_choice_kpro_f69e586 = [
    `Kpro of kprocedure (*tok*)
  | `Kfun of kfunction (*tok*)
]

type literalint = [
    `Imm_tok_pat_ec19546 of imm_tok_pat_ec19546
  | `Imm_tok_pat_d238afd of imm_tok_pat_d238afd
  | `Imm_tok_pat_f57674d of imm_tok_pat_f57674d
]

type operatorname_ = [
    `Kdot of Token.t (* "." *)
  | `Klt of Token.t (* "<" *)
  | `Keq of Token.t (* "=" *)
  | `Kneq of Token.t (* "<>" *)
  | `Kgt of Token.t (* ">" *)
  | `Klte of Token.t (* "<=" *)
  | `Kgte of Token.t (* ">=" *)
  | `Kadd of Token.t (* "+" *)
  | `Ksub of Token.t (* "-" *)
  | `Kmul of Token.t (* "*" *)
  | `Kfdiv of Token.t (* "/" *)
  | `Kdiv of kdiv (*tok*)
  | `Kmod of kmod (*tok*)
  | `Kass of Token.t (* ":=" *)
  | `Kor of kor (*tok*)
  | `Kxor of kxor (*tok*)
  | `Kand of kand (*tok*)
  | `Kshl of kshl (*tok*)
  | `Kshr of kshr (*tok*)
  | `Knot of knot (*tok*)
  | `Kin of kin (*tok*)
]

type exprisnot = (kis (*tok*) * knot (*tok*))

type asmbody =
  [
      `Id of identifier (*tok*)
    | `Pat_cafba40 of pat_cafba40
    | `Pat_3ea53fb of pat_3ea53fb
    | `Pat_f7c0026 of pat_f7c0026
  ]
    list (* one or more *)

type modulename = (
    (identifier (*tok*) * Token.t (* "." *)) list (* one or more *) option
  * identifier (*tok*)
)

type anon_opt_rep1_decl_COMMA_64c033f =
  (identifier (*tok*) * Token.t (* "," *)) list (* one or more *) option

type propaccessor = [
    `Id of identifier (*tok*)
  | `Prop of (propaccessor * Token.t (* "." *) * identifier (*tok*))
]

type label = (identifier (*tok*) * Token.t (* ":" *))

type anon_opt_rep1_type__COMMA_1201331 =
  (typeref_ * Token.t (* "," *)) list (* one or more *) option

and typeref_ = [
    `Id of identifier (*tok*)
  | `Type_3d7091c of (typeref_ * Token.t (* "." *) * typeref_)
  | `Type_90e8385 of (
        typeref_ * Token.t (* "<" *) * typerefargs * Token.t (* ">" *)
    )
  | `Type_cae2886 of (Token.t (* "^" *) * typeref_)
  | `Ppfr of ppfragmentexpr (*tok*)
]

and typerefargs = (anon_opt_rep1_type__COMMA_1201331 * typeref_)

type anon_choice_visi_5a3c750 = [
    `Visi of visibility
  | `Kreq of krequired (*tok*)
  | `Kopt of koptional (*tok*)
]

type literalnumber = [
    `Lite_65d24c1 of literalint
  | `Lite_bdeb053 of literalfloat
]

type asmtr = (kasm (*tok*) * asmbody option * kend (*tok*))

type anon_choice_modu_eefd7e7 = [
    `Modu of modulename
  | `Ppus of ppusesblock
  | `COMMA of Token.t (* "," *)
]

and ppusesblock = (
    tok_prec_p5_pat_0a9b8cd (*tok*)
  * anon_choice_modu_eefd7e7 list (* zero or more *)
  * (
        tok_prec_p5_pat_af36d87 (*tok*)
      * anon_choice_modu_eefd7e7 list (* zero or more *)
    )
      list (* zero or more *)
  * tok_prec_p5_pat_ef0cc7f (*tok*)
)

type decllabels = (
    klabel (*tok*) * anon_opt_rep1_decl_COMMA_64c033f * identifier (*tok*)
  * Token.t (* ";" *)
)

type literalstring_ = [
    `Pat_6c79139 of pat_6c79139
  | `Pat_cdd9bad of pat_cdd9bad
  | `Lite of (Token.t (* "#" *) * literalint)
]

type ppusesblockwithsemi = (
    tok_prec_p5_pat_0a9b8cd (*tok*)
  * anon_choice_modu_eefd7e7 list (* zero or more *)
  * Token.t (* ";" *)
  * (
        tok_prec_p5_pat_af36d87 (*tok*)
      * anon_choice_modu_eefd7e7 list (* zero or more *)
      * Token.t (* ";" *)
    )
      list (* zero or more *)
  * tok_prec_p5_pat_ef0cc7f (*tok*)
)

type literalstring = literalstring_ list (* one or more *)

type literal = [
    `Lite_4d69a90 of literalstring
  | `Lite_f64c399 of literalnumber
  | `Knil of knil (*tok*)
  | `Ktrue of ktrue (*tok*)
  | `Kfalse of kfalse (*tok*)
]

type subrangebound = [
    `Lite_f64c399 of literalnumber
  | `Choice_DASH_lite of (
        [ `DASH of Token.t (* "-" *) | `PLUS of Token.t (* "+" *) ]
      * literalnumber
    )
  | `Lite_4d69a90 of literalstring
  | `Type_ of typeref_
]

type hintdirective = [
    `Kdep_opt_lite of (kdeprecated (*tok*) * literalstring option)
  | `Kpla of kplatform (*tok*)
  | `Kexp of kexperimental (*tok*)
]

type moduleinfile = (modulename * kin (*tok*) * literalstring)

type usesclauseentry = [
    `Modu_5b9c6b7 of modulename
  | `Ppus of ppusesblock
  | `COMMA of Token.t (* "," *)
  | `Modu_fdf97ab of moduleinfile
  | `Semg_ellips of Token.t (* "..." *)
]

type anon_choice_modu_685a062 = [
    `Modu_5b9c6b7 of modulename
  | `Modu_fdf97ab of moduleinfile
]

type decluses = (
    kuses (*tok*)
  * [
        `Rep1_uses_SEMI of (
            usesclauseentry list (* one or more *)
          * Token.t (* ";" *)
        )
      | `Ppus of ppusesblockwithsemi
    ]
)

type anon_LPAR_opt_opt_rep1_type_COMMA_type_RPAR_116e8a8 = (
    Token.t (* "(" *)
  * (anon_opt_rep1_type_COMMA_9c6ebb1 * typeref) option
  * Token.t (* ")" *)
)

and anon_choice_bloc_1cb9769 = [ `Bloc of blocktr | `Asmtr of asmtr ]

and anon_choice_decl_fe4bcc4 = [
    `Decl_c64a659 of decltype
  | `Decl_a20e53a of declvar
  | `Decl_d45e488 of declconst
  | `Decl_6ec32a9 of declproc
  | `Decl_5f998b5 of declprop
  | `Decl_8dd77dd of declprocfwd
  | `Decl_497d63e of declfield
  | `Declts of decltypes
  | `Declvs of declvars
  | `Declcs of declconsts
  | `Defp of defproc
  | `Declus of decluses
  | `Declls of decllabels
  | `Decles of declexports
  | `Stmt of statement
  | `Ppbl of ppblock
  | `SEMI of Token.t (* ";" *)
  | `COMMA of Token.t (* "," *)
]

and anon_choice_exce_8373abe = [
    `Exce_66e7373 of exceptionhandler
  | `Exce_89cca21 of (
        kon (*tok*)
      * label option
      * typeref
      * kdo (*tok*)
      * statementtr option
    )
]

and anon_choice_expr_0b0705b = [ `Expr of expr | `Range of range ]

and anon_choice_expr_2fa3e6e = [
    `Expr of expr
  | `Vara of (
        kvar (*tok*)
      * identifier (*tok*)
      * (Token.t (* ":" *) * typeref) option
    )
]

and anon_choice_kelse_opt_COLON_opt_stat__c22ab7e = (
    anon_choice_kelse_d520062
  * Token.t (* ":" *) option
  * statementstr_ option
)

and anon_choice_kexc_opt_choice_stat__d8e7a89 = [
    `Kexc_opt_choice_stat_ of (
        kexcept (*tok*)
      * anon_choice_stat__f368a69 option
    )
  | `Kfin_opt_stat_ of (kfinally (*tok*) * statementstr_ option)
]

and anon_choice_proc__b0bc660 = [
    `Proc_ of procattribute_
  | `Proc of procexternal
]

and anon_choice_range_ff5eaed = [ `Range of range | `Expr of expr ]

and anon_choice_stat_2a62092 = [ `Stat of statementtr | `If of nestediftr ]

and anon_choice_stat__f368a69 = [
    `Stat_ of statementstr_
  | `Exce of (
        exceptionhandler list (* zero or more *)
      * anon_choice_exce_8373abe
      * exceptionelse option
    )
]

and anon_opt_kdep_opt_expr_9e396fa =
  (kdeprecated (*tok*) * expr option) option

and anon_opt_rep1_choice_expr_COMMA_d776c0e =
  (anon_choice_expr_0b0705b * Token.t (* "," *)) list (* one or more *)
    option

and anon_opt_rep1_decl_SEMI_bce1ef3 =
  (declarg * Token.t (* ";" *)) list (* one or more *) option

and anon_opt_rep1_expr_COMMA_39d8f3f =
  (expr * Token.t (* "," *)) list (* one or more *) option

and anon_opt_rep1_type_COMMA_9c6ebb1 =
  (typeref * Token.t (* "," *)) list (* one or more *) option

and arrinitializer = (
    Token.t (* "(" *)
  * (initializer_ * Token.t (* "," *)) list (* one or more *) option
  * initializer_
  * Token.t (* ")" *)
)

and assignment = (
    anon_choice_expr_2fa3e6e
  * [
        `Kass_82d56ca of Token.t (* ":=" *)
      | `Kass_ba783c9 of Token.t (* "+=" *)
      | `Kass_4c2e9df of Token.t (* "-=" *)
      | `Kass_f4032f6 of Token.t (* "*=" *)
      | `Kass_e6faaf6 of Token.t (* "/=" *)
    ]
  * expr
)

and blocktr = (kbegin (*tok*) * statementstr_ option * kend (*tok*))

and casecase = (caselabel * statement)

and casecasetr = (caselabel * statementtr option)

and caselabel = (
    anon_opt_rep1_choice_expr_COMMA_d776c0e * anon_choice_expr_0b0705b
  * Token.t (* ":" *)
)

and classdeclarations =
  [
      `Declts of decltypes
    | `Declvs of declvars
    | `Declcs of declconsts
    | `Decl_6ec32a9 of declproc
    | `Decl_5f998b5 of declprop
    | `Ppbl of ppblock
    | `Semg_ellips of Token.t (* "..." *)
  ]
    list (* one or more *)

and declarg = [
    `Choice_choice_kvar_opt_rep1_id_COMMA_id_opt_COLON_type_opt_defa of [
        `Choice_kvar_opt_rep1_id_COMMA_id_opt_COLON_type_opt_defa of (
            [
                `Kvar of kvar (*tok*)
              | `Kout of kout (*tok*)
              | `Kcon of kconstref (*tok*)
              | `Kconst_opt_rttias of (
                    kconst (*tok*)
                  * rttiattributes option
                )
            ]
          * anon_opt_rep1_decl_COMMA_64c033f
          * identifier (*tok*)
          * (Token.t (* ":" *) * type_ * defaultvalue option) option
        )
      | `Opt_rep1_id_COMMA_id_COLON_type_opt_defa of declvariantfield
    ]
  | `Semg_ellips of Token.t (* "..." *)
]

and declargs = (
    Token.t (* "(" *)
  * (anon_opt_rep1_decl_SEMI_bce1ef3 * declarg) option
  * Token.t (* ")" *)
)

and declclass = (
    kpacked (*tok*) option
  * [
        `Kclass of kclass (*tok*)
      | `Krec of krecord (*tok*)
      | `Kobj_46ccc5a of kobject (*tok*)
      | `Kobj_c680b59 of kobjcclass (*tok*)
      | `Kobj_3b0f491 of kobjccategory (*tok*)
      | `Kobj_ef2d785 of kobjcprotocol (*tok*)
    ]
  * [
        `Kabs of kabstract (*tok*)
      | `Ksea of ksealed (*tok*)
      | `Kext_opt_kname_expr of (
            kexternal (*tok*)
          * (kname (*tok*) * expr) option
        )
    ]
      option
  * anon_LPAR_opt_opt_rep1_type_COMMA_type_RPAR_116e8a8 option
  * declclass_ option
)

and declclass_ = (
    declfields option
  * classdeclarations option
  * [ `Decl of declsection | `Ppde of ppdeclsection ] list (* zero or more *)
  * declvariant option
  * kend (*tok*)
)

and declconst = (
    rttiattributes option
  * identifier (*tok*)
  * (Token.t (* ":" *) * type_) option
  * defaultvalue
  * hintdirective option
  * Token.t (* ";" *)
  * procattribute list (* zero or more *)
)

and declconsts = (
    kclass (*tok*) option
  * [ `Kconst of kconst (*tok*) | `Kres of kresourcestring (*tok*) ]
  * [ `Decl of declconst | `Ppbl of ppblock ] list (* zero or more *)
)

and declenumvalue = (identifier (*tok*) * defaultvalue option)

and declexport = (
    genericname
  * (anon_choice_kname_ba8a152 * expr) list (* zero or more *)
)

and declexports = (
    kexports (*tok*)
  * (
        (declexport * Token.t (* "," *)) list (* one or more *) option
      * declexport
    )
      option
  * Token.t (* ";" *)
)

and declfield = (
    rttiattributes option
  * anon_opt_rep1_decl_COMMA_64c033f
  * identifier (*tok*)
  * Token.t (* ":" *)
  * type_
  * defaultvalue option
  * Token.t (* ";" *)
)

and declfields =
  [ `Decl of declfield | `Ppbl of ppblock ] list (* one or more *)

and declhelper = (
    [
        `Kclass of kclass (*tok*)
      | `Krec of krecord (*tok*)
      | `Ktype of ktype (*tok*)
    ]
  * khelper (*tok*)
  * anon_LPAR_opt_opt_rep1_type_COMMA_type_RPAR_116e8a8 option
  * kfor (*tok*)
  * typeref
  * declclass_
)

and declintf = (
    kpacked (*tok*) option
  * [ `Kint of kinterface (*tok*) | `Kdis of kdispinterface (*tok*) ]
  * anon_LPAR_opt_opt_rep1_type_COMMA_type_RPAR_116e8a8 option
  * guid option
  * declclass_ option
)

and decloperator = (
    kclass (*tok*) option
  * koperator (*tok*)
  * operatorname
  * declargs option
  * identifier (*tok*) option
  * (Token.t (* ":" *) * type_) option
  * defaultvalue option
  * Token.t (* ";" *)
  * procattributenoext list (* zero or more *)
)

and declproc = (
    rttiattributes option
  * [ `Decl_ of declproc_ | `Decl of decloperator ]
)

and declproc_ = (
    kgeneric (*tok*) option
  * kclass (*tok*) option
  * [
        `Kpro of kprocedure (*tok*)
      | `Kfun of kfunction (*tok*)
      | `Kcon of kconstructor (*tok*)
      | `Kdes of kdestructor (*tok*)
    ]
  * genericname
  * declargs option
  * (Token.t (* ":" *) * typeref) option
  * anon_choice_kstd_a801c0a option
  * defaultvalue option
  * Token.t (* ";" *)
  * procattributenoext list (* zero or more *)
)

and declprocfwd = (
    declproc_
  * [
        `Kfor_SEMI of (kforward (*tok*) * Token.t (* ";" *))
      | `Proc of procexternal
    ]
  * procattribute list (* zero or more *)
)

and declprop = (
    rttiattributes option
  * kclass (*tok*) option
  * kproperty (*tok*)
  * identifier (*tok*)
  * declpropargs option
  * (Token.t (* ":" *) * type_) option
  * [
        `Kindex_expr of (kindex (*tok*) * expr)
      | `Kdis_expr of (kdispid (*tok*) * expr)
      | `Kread_prop of (kread (*tok*) * propaccessor)
      | `Kwrite_prop of (kwrite (*tok*) * propaccessor)
      | `Kimpls_rep_expr_COMMA_expr of (
            kimplements (*tok*)
          * (expr * Token.t (* "," *)) list (* zero or more *)
          * expr
        )
      | `Kdef_expr of (kdefault (*tok*) * expr)
      | `Ksto_expr of (kstored (*tok*) * expr)
      | `Knod of knodefault (*tok*)
      | `Krea of kreadonly (*tok*)
      | `Kwri of kwriteonly (*tok*)
    ]
      list (* zero or more *)
  * Token.t (* ";" *)
  * procattribute list (* zero or more *)
)

and declpropargs = (
    Token.t (* "[" *)
  * (anon_opt_rep1_decl_SEMI_bce1ef3 * declarg) option
  * Token.t (* "]" *)
)

and declsection = (
    kstrict (*tok*) option
  * anon_choice_visi_5a3c750
  * declfields option
  * classdeclarations option
)

and decltype = (
    rttiattributes option
  * kgeneric (*tok*) option
  * genericname
  * Token.t (* "=" *)
  * [
        `Opt_ktype_type of (ktype (*tok*) option * type_)
      | `Choice_type of [ `Type of type_ ]
      | `Decl_7f52a4c of declclass
      | `Decl_acc2c34 of declintf
      | `Decl_11ac719 of declhelper
    ]
  * Token.t (* ";" *)
  * procattribute list (* zero or more *)
)

and decltypes = (
    ktype (*tok*)
  * [
        `Decl of decltype
      | `Ppbl of ppblock
      | `Semg_ellips of Token.t (* "..." *)
    ]
      list (* zero or more *)
)

and declvar = (
    rttiattributes option
  * anon_opt_rep1_decl_COMMA_64c033f
  * identifier (*tok*)
  * Token.t (* ":" *)
  * type_
  * [ `Kabs_ref of (kabsolute (*tok*) * ref) | `Defa of defaultvalue ] option
  * Token.t (* ";" *)
  * [ `Proc_7cf9cd2 of procattribute | `Proc_8049b7e of procexternal ]
      list (* zero or more *)
)

and declvariant = (
    kcase (*tok*)
  * label option
  * typeref
  * kof (*tok*)
  * (declvariantclause * Token.t (* ";" *)) list (* one or more *) option
  * declvariantclause
  * Token.t (* ";" *) option
)

and declvariantclause = (
    caselabel
  * Token.t (* "(" *)
  * [
        `Opt_opt_rep1_decl_SEMI_decl_opt_SEMI_decl of (
            (
                (declvariantfield * Token.t (* ";" *)) list (* one or more *)
                  option
              * declvariantfield
            )
              option
          * (Token.t (* ";" *) * declvariant) option
        )
      | `Decl of declvariant
    ]
  * Token.t (* ";" *) option
  * Token.t (* ")" *)
)

and declvariantfield = (
    anon_opt_rep1_decl_COMMA_64c033f
  * identifier (*tok*)
  * Token.t (* ":" *)
  * type_
  * defaultvalue option
)

and declvars = (
    kclass (*tok*) option
  * [ `Kvar of kvar (*tok*) | `Kthr of kthreadvar (*tok*) ]
  * [
        `Decl of declvar
      | `Ppbl of ppblock
      | `Semg_ellips of Token.t (* "..." *)
    ]
      list (* zero or more *)
)

and defaultvalue = (Token.t (* "=" *) * initializer_)

and definition = [
    `Declts of decltypes
  | `Declvs of declvars
  | `Declcs of declconsts
  | `Defp of defproc
  | `Decl of declprocfwd
  | `Declls of decllabels
  | `Declus of decluses
  | `Decles of declexports
  | `Ppbl of ppblock
  | `Bloc of blocktr
  | `Semg_ellips of Token.t (* "..." *)
]

and definitions = definition list (* one or more *)

and defproc = (
    declproc
  * [
        `Opt_defins_choice_bloc_SEMI of (
            definitions option
          * anon_choice_bloc_1cb9769
          * Token.t (* ";" *)
        )
      | `Tok_prec_p5_pat_6f93d17_opt_defins_choice_bloc_SEMI_rep_tok_prec_p5_pat_b66c674_opt_defins_choice_bloc_SEMI_tok_prec_p5_pat_9f5699f of (
            tok_prec_p5_pat_6f93d17 (*tok*)
          * definitions option
          * anon_choice_bloc_1cb9769
          * Token.t (* ";" *)
          * (
                tok_prec_p5_pat_b66c674 (*tok*)
              * definitions option
              * anon_choice_bloc_1cb9769
              * Token.t (* ";" *)
            )
              list (* zero or more *)
          * tok_prec_p5_pat_9f5699f (*tok*)
        )
    ]
)

and exceptionelse = (
    kelse (*tok*)
  * statement list (* zero or more *)
  * statement
)

and exceptionhandler = (
    kon (*tok*)
  * label option
  * typeref
  * kdo (*tok*)
  * statement
)

and expr = [
    `Ref of ref
  | `Expr_ef29a06 of exprbinary
  | `Expr_5c4be6d of exprunary
  | `Expr_3037366 of (
        kif (*tok*) * expr * kthen (*tok*) * expr * kelse (*tok*) * expr
    )
]

and exprargs = (
    (expr * legacyformat option * Token.t (* "," *)) list (* one or more *)
      option
  * expr
  * legacyformat option
)

and exprbinary = [
    `Expr_klt_expr of (expr * Token.t (* "<" *) * expr)
  | `Ref_klt_expr of (ref * Token.t (* "<" *) * expr)
  | `Expr_keq_expr of (expr * Token.t (* "=" *) * expr)
  | `Expr_kneq_expr of (expr * Token.t (* "<>" *) * expr)
  | `Expr_kgt_expr of (expr * Token.t (* ">" *) * expr)
  | `Expr_klte_expr of (expr * Token.t (* "<=" *) * expr)
  | `Expr_kgte_expr of (expr * Token.t (* ">=" *) * expr)
  | `Expr_kin_expr of (expr * kin (*tok*) * expr)
  | `Expr_kis_expr of (expr * kis (*tok*) * expr)
  | `Expr_knot_kin_expr of (expr * knot (*tok*) * kin (*tok*) * expr)
  | `Expr_expr_expr of (expr * exprisnot * expr)
  | `Expr_kadd_expr of (expr * Token.t (* "+" *) * expr)
  | `Expr_ksub_expr of (expr * Token.t (* "-" *) * expr)
  | `Expr_kor_expr of (expr * kor (*tok*) * expr)
  | `Expr_kxor_expr of (expr * kxor (*tok*) * expr)
  | `Expr_kmul_expr of (expr * Token.t (* "*" *) * expr)
  | `Expr_kfdiv_expr of (expr * Token.t (* "/" *) * expr)
  | `Expr_kdiv_expr of (expr * kdiv (*tok*) * expr)
  | `Expr_kmod_expr of (expr * kmod (*tok*) * expr)
  | `Expr_kand_expr of (expr * kand (*tok*) * expr)
  | `Expr_kshl_expr of (expr * kshl (*tok*) * expr)
  | `Expr_kshr_expr of (expr * kshr (*tok*) * expr)
]

and exprunary = [
    `Knot_expr of (knot (*tok*) * expr)
  | `Kadd_expr of (Token.t (* "+" *) * expr)
  | `Ksub_expr of (Token.t (* "-" *) * expr)
  | `Kat_expr of (Token.t (* "@" *) * expr)
]

and genericarg = (
    anon_opt_rep1_decl_COMMA_64c033f
  * identifier (*tok*)
  * (Token.t (* ":" *) * typeref) option
  * defaultvalue option
)

and genericargs = (
    (genericarg * Token.t (* ";" *)) list (* one or more *) option
  * genericarg
)

and genericname = [
    `Id of identifier (*tok*)
  | `Gene_067353e of (genericname * Token.t (* "." *) * genericname)
  | `Gene_4088af4 of (
        genericname * Token.t (* "<" *) * genericargs * Token.t (* ">" *)
    )
]

and guid = (Token.t (* "[" *) * ref * Token.t (* "]" *))

and if_ = (kif (*tok*) * expr * kthen (*tok*) * statement)

and initializer_ = [
    `Expr of expr
  | `Reci of recinitializer
  | `Arri of arrinitializer
]

and legacyformat = (Token.t (* ":" *) * expr) list (* one or more *)

and nestediftr = if_

and operatordot = (genericname * Token.t (* "." *) * operatorname_)

and operatorname = [
    `Gene of genericname
  | `Oper_ of operatorname_
  | `Oper of operatordot
]

and ppblock = (
    ppif (*tok*)
  * anon_choice_decl_fe4bcc4 list (* zero or more *)
  * (ppelse (*tok*) * anon_choice_decl_fe4bcc4 list (* zero or more *))
      list (* zero or more *)
  * ppendif (*tok*)
)

and ppdeclsection = (
    ppif (*tok*)
  * kstrict (*tok*) option
  * anon_choice_visi_5a3c750
  * ppendif (*tok*)
  * declfields option
  * classdeclarations option
)

and procattribute = [
    `Proc__SEMI of (procattribute_ * Token.t (* ";" *))
  | `LBRACK_opt_opt_rep1_choice_proc__COMMA_choice_proc__RBRACK_SEMI of (
        Token.t (* "[" *)
      * (
            (anon_choice_proc__b0bc660 * Token.t (* "," *))
              list (* one or more *)
              option
          * anon_choice_proc__b0bc660
        )
          option
      * Token.t (* "]" *)
      * Token.t (* ";" *)
    )
]

and procattribute_ = [
    `Ksta of kstatic (*tok*)
  | `Kvir of kvirtual (*tok*)
  | `Kdyn of kdynamic (*tok*)
  | `Kabs of kabstract (*tok*)
  | `Kove_98086b9 of koverride (*tok*)
  | `Kove_a43f97e of koverload (*tok*)
  | `Krei of kreintroduce (*tok*)
  | `Kinl of kinline (*tok*)
  | `Kstd of kstdcall (*tok*)
  | `Kcdecl of kcdecl (*tok*)
  | `Kpas of kpascal (*tok*)
  | `Kreg of kregister (*tok*)
  | `Ksaf of ksafecall (*tok*)
  | `Kass of kassembler (*tok*)
  | `Knor of knoreturn (*tok*)
  | `Klocal of klocal (*tok*)
  | `Kfar of kfar (*tok*)
  | `Knear of knear (*tok*)
  | `Kdef of kdefault (*tok*)
  | `Knod of knodefault (*tok*)
  | `Kdep of kdeprecated (*tok*)
  | `Kexp of kexperimental (*tok*)
  | `Choice_kmes_opt_kname_expr of (
        [
            `Kmes_opt_kname of (kmessage (*tok*) * kname (*tok*) option)
          | `Kdep of kdeprecated (*tok*)
        ]
      * expr
    )
  | `Kpla of kplatform (*tok*)
  | `Kuni of kunimplemented (*tok*)
  | `Kcpp of kcppdecl (*tok*)
  | `Kcvar of kcvar (*tok*)
  | `Kmwp of kmwpascal (*tok*)
  | `Knos of knostackframe (*tok*)
  | `Kint of kinterrupt (*tok*)
  | `Kioc of kiocheck (*tok*)
  | `Khar of khardfloat (*tok*)
  | `Ksof of ksoftfloat (*tok*)
  | `Kms_abi_defa of kms_abi_default (*tok*)
  | `Kms_abi_cdecl of kms_abi_cdecl (*tok*)
  | `Ksaves of ksaveregisters (*tok*)
  | `Ksysv_abi_defa of ksysv_abi_default (*tok*)
  | `Ksysv_abi_cdecl of ksysv_abi_cdecl (*tok*)
  | `Kvec of kvectorcall (*tok*)
  | `Kvaras of kvarargs (*tok*)
  | `Kwin of kwinapi (*tok*)
  | `Kpub of kpublic (*tok*)
  | `Choice_kexp_expr of (
        [
            `Kexp of kexport (*tok*)
          | `Kalias_COLON of (kalias (*tok*) * Token.t (* ":" *))
          | `Kpub_kname of (kpublic (*tok*) * kname (*tok*))
        ]
      * expr
    )
  | `Kdis_expr of (kdispid (*tok*) * expr)
]

and procattributenoext = [
    `Choice_proc__SEMI of (
        [
            `Proc_ of procattribute_
          | `Ppif_proc__rep_ppelse_proc__ppen of (
                ppif (*tok*)
              * procattribute_
              * (ppelse (*tok*) * procattribute_) list (* zero or more *)
              * ppendif (*tok*)
            )
        ]
      * Token.t (* ";" *)
    )
  | `LBRACK_opt_opt_rep1_choice_proc__SEMI_choice_proc__RBRACK_SEMI of (
        Token.t (* "[" *)
      * (
            ([ `Proc_ of procattribute_ ] * Token.t (* ";" *))
              list (* one or more *)
              option
          * [ `Proc_ of procattribute_ ]
        )
          option
      * Token.t (* "]" *)
      * Token.t (* ";" *)
    )
]

and procexternal = (
    kexternal (*tok*)
  * expr option
  * (anon_choice_kname_ba8a152 * expr) option
  * kdelayed (*tok*) option
  * Token.t (* ";" *)
)

and range = (expr * Token.t (* ".." *) * expr)

and recinitializer = (
    Token.t (* "(" *)
  * (recinitializerfield * Token.t (* ";" *)) list (* zero or more *)
  * recinitializerfield
  * Token.t (* ";" *) option
  * Token.t (* ")" *)
)

and recinitializerfield = [
    `Id_COLON_init of (identifier (*tok*) * Token.t (* ":" *) * initializer_)
  | `Init of initializer_
]

and ref = [
    `Choice_kspe_id of [
        `Kspe_id of (kspecialize (*tok*) * identifier (*tok*))
      | `Kspe of kspecialize (*tok*)
    ]
  | `Id of identifier (*tok*)
  | `Lit of literal
  | `Inhe of (kinherited (*tok*) * identifier (*tok*) option)
  | `Expr_4f305a9 of (ref * Token.t (* "." *) * ref)
  | `Exprbs of (
        Token.t (* "[" *)
      * (anon_opt_rep1_choice_expr_COMMA_d776c0e * anon_choice_expr_0b0705b)
          option
      * Token.t (* "]" *)
    )
  | `Exprps of (Token.t (* "(" *) * expr * Token.t (* ")" *))
  | `Expr_2b043f4 of (ref * Token.t (* "[" *) * exprargs * Token.t (* "]" *))
  | `Expr_31f068a of (
        ref
      * Token.t (* "(" *)
      * exprargs option
      * Token.t (* ")" *)
    )
  | `Expr_abfcfa5 of (expr * Token.t (* "^" *))
  | `Expras of (expr * kas (*tok*) * expr)
  | `Expr_1293f4f of (
        ref * Token.t (* "<" *) * anon_opt_rep1_type__COMMA_1201331
      * typeref_ * Token.t (* ">" *)
    )
  | `Lambda of (
        anon_choice_kpro_f69e586
      * declargs option
      * (Token.t (* ":" *) * typeref) option
      * definitions option
      * anon_choice_bloc_1cb9769
    )
  | `Ppfr of ppfragmentexpr (*tok*)
  | `Semg_ellips of Token.t (* "..." *)
  | `Deep_ellips of (Token.t (* "<..." *) * expr * Token.t (* "...>" *))
]

and rttiattributes =
  (
      Token.t (* "[" *)
    * label option
    * ((ref * Token.t (* "," *)) list (* one or more *) option * ref) option
    * Token.t (* "]" *)
  )
    list (* one or more *)

and statement = [
    `SEMI of Token.t (* ";" *)
  | `Assign_SEMI of (assignment * Token.t (* ";" *))
  | `Vardef_SEMI of (vardef * Token.t (* ";" *))
  | `Stmt_ of statement_
  | `If of nestediftr
  | `Ifelse of (
        kif (*tok*)
      * expr
      * kthen (*tok*)
      * anon_choice_stat_2a62092 option
      * kelse (*tok*)
      * statement
    )
  | `While of (kwhile (*tok*) * expr * kdo (*tok*) * statement)
  | `Repeat of (
        krepeat (*tok*)
      * statementstr_ option
      * kuntil (*tok*)
      * expr
      * Token.t (* ";" *)
    )
  | `For of (
        kfor (*tok*) * assignment * anon_choice_kto_86c5a40 * expr
      * kdo (*tok*) * statement
    )
  | `Fore of (
        kfor (*tok*) * anon_choice_expr_2fa3e6e * kin (*tok*) * expr
      * kdo (*tok*) * statement
    )
  | `Try of (
        ktry (*tok*)
      * statementstr_ option
      * anon_choice_kexc_opt_choice_stat__d8e7a89
      * kend (*tok*)
      * Token.t (* ";" *)
    )
  | `Case of (
        kcase (*tok*)
      * expr
      * kof (*tok*)
      * casecase list (* zero or more *)
      * casecasetr option
      * anon_choice_kelse_opt_COLON_opt_stat__c22ab7e option
      * kend (*tok*)
      * Token.t (* ";" *)
    )
  | `Blk of (
        kbegin (*tok*)
      * statementstr_ option
      * kend (*tok*)
      * Token.t (* ";" *)
    )
  | `With of (
        kwith (*tok*) * anon_opt_rep1_expr_COMMA_39d8f3f * expr * kdo (*tok*)
      * statement
    )
  | `Raise of (
        kraise (*tok*)
      * expr option
      * (kraiseat (*tok*) * expr) option
      * Token.t (* ";" *)
    )
  | `Goto of (kgoto (*tok*) * identifier (*tok*) * Token.t (* ";" *))
  | `Asm of (
        kasm (*tok*)
      * asmbody option
      * kend (*tok*)
      * Token.t (* ";" *)
    )
  | `Semg_ellips of Token.t (* "..." *)
]

and statement_ = [ `Expr_SEMI of (expr * Token.t (* ";" *)) ]

and statementstr = (
    [
        `Stmt of statement
      | `Label of label
      | `Ppbl of ppblock
      | `Ppfr of ppfragmentstmt (*tok*)
    ]
      list (* zero or more *)
  * [
        `Stat of statementtr
      | `Stmt of statement
      | `Ppbl of ppblock
      | `Ppfr of ppfragmentstmt (*tok*)
    ]
)

and statementstr_ = statementstr

and statementtr = [
    `Assign of assignment
  | `Vardef of vardef
  | `Stat_ of statementtr_
  | `Iftr of (kif (*tok*) * expr * kthen (*tok*) * statementtr option)
  | `Ifel of (
        kif (*tok*)
      * expr
      * kthen (*tok*)
      * anon_choice_stat_2a62092 option
      * kelse (*tok*)
      * statementtr option
    )
  | `Whil of (kwhile (*tok*) * expr * kdo (*tok*) * statementtr option)
  | `Repe of (krepeat (*tok*) * statementstr_ option * kuntil (*tok*) * expr)
  | `Fortr of (
        kfor (*tok*)
      * assignment
      * anon_choice_kto_86c5a40
      * expr
      * kdo (*tok*)
      * statementtr option
    )
  | `Fore of (
        kfor (*tok*)
      * anon_choice_expr_2fa3e6e
      * kin (*tok*)
      * expr
      * kdo (*tok*)
      * statementtr option
    )
  | `Trytr of (
        ktry (*tok*)
      * statementstr_ option
      * anon_choice_kexc_opt_choice_stat__d8e7a89
      * kend (*tok*)
    )
  | `Casetr of (
        kcase (*tok*)
      * expr
      * kof (*tok*)
      * casecase list (* zero or more *)
      * casecasetr option
      * anon_choice_kelse_opt_COLON_opt_stat__c22ab7e option
      * kend (*tok*)
    )
  | `Bloc of blocktr
  | `Withtr of (
        kwith (*tok*)
      * anon_opt_rep1_expr_COMMA_39d8f3f
      * expr
      * kdo (*tok*)
      * statementtr option
    )
  | `Rais of (
        kraise (*tok*)
      * expr option
      * (kraiseat (*tok*) * expr) option
    )
  | `Gototr of (kgoto (*tok*) * identifier (*tok*))
  | `Asmtr of asmtr
]

and statementtr_ = [ `Expr of expr ]

and type_ = [
    `Type of typeref
  | `Decl_172a5fa of (kclass (*tok*) * kof (*tok*) * typeref)
  | `Decl_b2059ac of (
        Token.t (* "(" *)
      * (declenumvalue * Token.t (* "," *)) list (* one or more *) option
      * declenumvalue
      * Token.t (* ")" *)
    )
  | `Decl_9b757b1 of (kset (*tok*) * kof (*tok*) * type_)
  | `Decl_fb3a596 of (
        kpacked (*tok*) option
      * karray (*tok*)
      * (
            Token.t (* "[" *)
          * (
                (anon_choice_range_ff5eaed * Token.t (* "," *))
                  list (* one or more *)
                  option
              * anon_choice_range_ff5eaed
            )
              option
          * Token.t (* "]" *)
        )
          option
      * kof (*tok*)
      * type_
    )
  | `Decl_d33f432 of (kfile (*tok*) * (kof (*tok*) * type_) option)
  | `Decl_4e1d441 of (
        kstring (*tok*)
      * (Token.t (* "[" *) * [ `Expr of expr ] * Token.t (* "]" *)) option
      * anon_opt_kdep_opt_expr_9e396fa
    )
  | `Decl_4eec7e9 of (
        (kreference (*tok*) * kto (*tok*)) option
      * anon_choice_kpro_f69e586
      * declargs option
      * (Token.t (* ":" *) * typeref) option
      * (kof (*tok*) * kobject (*tok*)) option
      * anon_choice_kstd_a801c0a option
    )
  | `Decl_0ebbf4b of (subrangebound * Token.t (* ".." *) * subrangebound)
  | `Decl_dd9f703 of (kpacked (*tok*) option * krecord (*tok*) * declclass_)
]

and typeref = (
    kspecialize (*tok*) option
  * typeref_
  * anon_opt_kdep_opt_expr_9e396fa
)

and vardef = (
    kvar (*tok*) * identifier (*tok*) * Token.t (* ":" *) * typeref
)

type library = (
    klibrary (*tok*)
  * modulename
  * Token.t (* ";" *)
  * definitions option
  * [ `Bloc of blocktr | `Kend of kend (*tok*) ]
  * Token.t (* "." *)
)

type declarations =
  [
      `Declts of decltypes
    | `Declvs of declvars
    | `Declcs of declconsts
    | `Decl_6ec32a9 of declproc
    | `Decl_5f998b5 of declprop
    | `Decl_8dd77dd of declprocfwd
    | `Declus of decluses
    | `Declls of decllabels
    | `Decles of declexports
    | `Ppbl of ppblock
    | `Semg_ellips of Token.t (* "..." *)
  ]
    list (* one or more *)

type implementation = (kimplementation (*tok*) * definitions option)

type finalization = (kfinalization (*tok*) * statementstr_ option)

type program = (
    kprogram (*tok*)
  * modulename
  * Token.t (* ";" *)
  * definitions option
  * blocktr
  * Token.t (* "." *)
)

type statements =
  [
      `Vardef of vardef
    | `Stmt of statement
    | `Label of label
    | `Ppbl of ppblock
    | `Ppfr of ppfragmentstmt (*tok*)
  ]
    list (* one or more *)

type initialization = (kinitialization (*tok*) * statementstr_ option)

type interface = (kinterface (*tok*) * declarations option)

type unit_ = (
    kunit (*tok*)
  * modulename
  * Token.t (* ";" *)
  * [
        `Inte of interface
      | `Impl of implementation
      | `Init of initialization
      | `Fina of finalization
    ]
      list (* zero or more *)
  * kend (*tok*) option
  * Token.t (* "." *)
)

type root = [
    `Opt_choice_prog of
      [
          `Prog of program
        | `Libr of library
        | `Unit of unit_
        | `Defins of definitions
      ]
        option
  | `Pack of (
        kpackage (*tok*)
      * modulename
      * Token.t (* ";" *)
      * (
            krequires (*tok*)
          * (modulename * Token.t (* "," *)) list (* zero or more *)
          * modulename
          * Token.t (* ";" *)
        )
          option
      * (
            kcontains (*tok*)
          * (anon_choice_modu_685a062 * Token.t (* "," *))
              list (* zero or more *)
          * anon_choice_modu_685a062
          * Token.t (* ";" *)
        )
          option
      * kend (*tok*)
      * Token.t (* "." *)
    )
  | `Semg_exp of (Token.t (* "__SEMGREP_EXPRESSION" *) * expr)
  | `Semg_stmts of (Token.t (* "__SEMGREP_STATEMENTS" *) * statementstr_)
  | `Semg_declas of (
        Token.t (* "__SEMGREP_DECLARATIONS" *)
      * [
            `Decl_c64a659 of decltype
          | `Decl_a20e53a of declvar
          | `Decl_d45e488 of declconst
          | `Decl_497d63e of declfield
          | `Decl_5f998b5 of declprop
          | `Decl_6ec32a9 of declproc
          | `Decl_8dd77dd of declprocfwd
          | `Declts of decltypes
          | `Declvs of declvars
          | `Declcs of declconsts
          | `Declus of decluses
          | `Semg_ellips of Token.t (* "..." *)
        ]
          list (* one or more *)
    )
]

type kat (* inlined *) = Token.t (* "@" *)

type ppdirective (* inlined *) = Token.t

type comment (* inlined *) = Token.t

type klt (* inlined *) = Token.t (* "<" *)

type kfdiv (* inlined *) = Token.t (* "/" *)

type kneq (* inlined *) = Token.t (* "<>" *)

type kassignadd (* inlined *) = Token.t (* "+=" *)

type khat (* inlined *) = Token.t (* "^" *)

type kdot (* inlined *) = Token.t (* "." *)

type ksub (* inlined *) = Token.t (* "-" *)

type kmul (* inlined *) = Token.t (* "*" *)

type keq (* inlined *) = Token.t (* "=" *)

type klte (* inlined *) = Token.t (* "<=" *)

type kassignsub (* inlined *) = Token.t (* "-=" *)

type kassignmul (* inlined *) = Token.t (* "*=" *)

type kenddot (* inlined *) = Token.t (* "." *)

type kassign (* inlined *) = Token.t (* ":=" *)

type kgt (* inlined *) = Token.t (* ">" *)

type semgrep_ellipsis (* inlined *) = Token.t (* "..." *)

type kadd (* inlined *) = Token.t (* "+" *)

type space (* inlined *) = Token.t (* pattern [\s\r\n\t﻿]+ *)

type kgte (* inlined *) = Token.t (* ">=" *)

type kassigndiv (* inlined *) = Token.t (* "/=" *)

type decllabel (* inlined *) = identifier (*tok*)

type gototr (* inlined *) = (kgoto (*tok*) * identifier (*tok*))

type goto (* inlined *) = (
    kgoto (*tok*) * identifier (*tok*) * Token.t (* ";" *)
)

type inherited (* inlined *) = (
    kinherited (*tok*)
  * identifier (*tok*) option
)

type propaccessordot (* inlined *) = (
    propaccessor * Token.t (* "." *) * identifier (*tok*)
)

type typerefdot (* inlined *) = (typeref_ * Token.t (* "." *) * typeref_)

type typerefptr (* inlined *) = (Token.t (* "^" *) * typeref_)

type typereftpl (* inlined *) = (
    typeref_ * Token.t (* "<" *) * typerefargs * Token.t (* ">" *)
)

type literalchar (* inlined *) = (Token.t (* "#" *) * literalint)

type asm (* inlined *) = (
    kasm (*tok*)
  * asmbody option
  * kend (*tok*)
  * Token.t (* ";" *)
)

type declsubrange (* inlined *) = (
    subrangebound * Token.t (* ".." *) * subrangebound
)

type package (* inlined *) = (
    kpackage (*tok*)
  * modulename
  * Token.t (* ";" *)
  * (
        krequires (*tok*)
      * (modulename * Token.t (* "," *)) list (* zero or more *)
      * modulename
      * Token.t (* ";" *)
    )
      option
  * (
        kcontains (*tok*)
      * (anon_choice_modu_685a062 * Token.t (* "," *))
          list (* zero or more *)
      * anon_choice_modu_685a062
      * Token.t (* ";" *)
    )
      option
  * kend (*tok*)
  * Token.t (* "." *)
)

type block (* inlined *) = (
    kbegin (*tok*)
  * statementstr_ option
  * kend (*tok*)
  * Token.t (* ";" *)
)

type case (* inlined *) = (
    kcase (*tok*)
  * expr
  * kof (*tok*)
  * casecase list (* zero or more *)
  * casecasetr option
  * anon_choice_kelse_opt_COLON_opt_stat__c22ab7e option
  * kend (*tok*)
  * Token.t (* ";" *)
)

type casetr (* inlined *) = (
    kcase (*tok*)
  * expr
  * kof (*tok*)
  * casecase list (* zero or more *)
  * casecasetr option
  * anon_choice_kelse_opt_COLON_opt_stat__c22ab7e option
  * kend (*tok*)
)

type declarray (* inlined *) = (
    kpacked (*tok*) option
  * karray (*tok*)
  * (
        Token.t (* "[" *)
      * (
            (anon_choice_range_ff5eaed * Token.t (* "," *))
              list (* one or more *)
              option
          * anon_choice_range_ff5eaed
        )
          option
      * Token.t (* "]" *)
    )
      option
  * kof (*tok*)
  * type_
)

type declenum (* inlined *) = (
    Token.t (* "(" *)
  * (declenumvalue * Token.t (* "," *)) list (* one or more *) option
  * declenumvalue
  * Token.t (* ")" *)
)

type declfile (* inlined *) = (kfile (*tok*) * (kof (*tok*) * type_) option)

type declmetaclass (* inlined *) = (kclass (*tok*) * kof (*tok*) * typeref)

type declprocref (* inlined *) = (
    (kreference (*tok*) * kto (*tok*)) option
  * anon_choice_kpro_f69e586
  * declargs option
  * (Token.t (* ":" *) * typeref) option
  * (kof (*tok*) * kobject (*tok*)) option
  * anon_choice_kstd_a801c0a option
)

type declrecordinline (* inlined *) = (
    kpacked (*tok*) option
  * krecord (*tok*)
  * declclass_
)

type declset (* inlined *) = (kset (*tok*) * kof (*tok*) * type_)

type declstring (* inlined *) = (
    kstring (*tok*)
  * (Token.t (* "[" *) * [ `Expr of expr ] * Token.t (* "]" *)) option
  * anon_opt_kdep_opt_expr_9e396fa
)

type deep_ellipsis (* inlined *) = (
    Token.t (* "<..." *) * expr * Token.t (* "...>" *)
)

type exceptionhandlerstr (* inlined *) = (
    exceptionhandler list (* zero or more *)
  * anon_choice_exce_8373abe
  * exceptionelse option
)

type exceptionhandlertr (* inlined *) = (
    kon (*tok*)
  * label option
  * typeref
  * kdo (*tok*)
  * statementtr option
)

type expras (* inlined *) = (expr * kas (*tok*) * expr)

type exprbrackets (* inlined *) = (
    Token.t (* "[" *)
  * (anon_opt_rep1_choice_expr_COMMA_d776c0e * anon_choice_expr_0b0705b)
      option
  * Token.t (* "]" *)
)

type exprcall (* inlined *) = (
    ref
  * Token.t (* "(" *)
  * exprargs option
  * Token.t (* ")" *)
)

type exprconditional (* inlined *) = (
    kif (*tok*) * expr * kthen (*tok*) * expr * kelse (*tok*) * expr
)

type exprderef (* inlined *) = (expr * Token.t (* "^" *))

type exprdot (* inlined *) = (ref * Token.t (* "." *) * ref)

type exprparens (* inlined *) = (
    Token.t (* "(" *) * expr * Token.t (* ")" *)
)

type exprsubscript (* inlined *) = (
    ref * Token.t (* "[" *) * exprargs * Token.t (* "]" *)
)

type exprtpl (* inlined *) = (
    ref * Token.t (* "<" *) * anon_opt_rep1_type__COMMA_1201331 * typeref_
  * Token.t (* ">" *)
)

type for_ (* inlined *) = (
    kfor (*tok*) * assignment * anon_choice_kto_86c5a40 * expr * kdo (*tok*)
  * statement
)

type foreach (* inlined *) = (
    kfor (*tok*) * anon_choice_expr_2fa3e6e * kin (*tok*) * expr
  * kdo (*tok*) * statement
)

type foreachtr (* inlined *) = (
    kfor (*tok*)
  * anon_choice_expr_2fa3e6e
  * kin (*tok*)
  * expr
  * kdo (*tok*)
  * statementtr option
)

type fortr (* inlined *) = (
    kfor (*tok*)
  * assignment
  * anon_choice_kto_86c5a40
  * expr
  * kdo (*tok*)
  * statementtr option
)

type genericdot (* inlined *) = (
    genericname * Token.t (* "." *) * genericname
)

type generictpl (* inlined *) = (
    genericname * Token.t (* "<" *) * genericargs * Token.t (* ">" *)
)

type ifelse (* inlined *) = (
    kif (*tok*)
  * expr
  * kthen (*tok*)
  * anon_choice_stat_2a62092 option
  * kelse (*tok*)
  * statement
)

type ifelsetr (* inlined *) = (
    kif (*tok*)
  * expr
  * kthen (*tok*)
  * anon_choice_stat_2a62092 option
  * kelse (*tok*)
  * statementtr option
)

type iftr (* inlined *) = (
    kif (*tok*)
  * expr
  * kthen (*tok*)
  * statementtr option
)

type lambda (* inlined *) = (
    anon_choice_kpro_f69e586
  * declargs option
  * (Token.t (* ":" *) * typeref) option
  * definitions option
  * anon_choice_bloc_1cb9769
)

type raise (* inlined *) = (
    kraise (*tok*)
  * expr option
  * (kraiseat (*tok*) * expr) option
  * Token.t (* ";" *)
)

type raisetr (* inlined *) = (
    kraise (*tok*)
  * expr option
  * (kraiseat (*tok*) * expr) option
)

type repeat (* inlined *) = (
    krepeat (*tok*)
  * statementstr_ option
  * kuntil (*tok*)
  * expr
  * Token.t (* ";" *)
)

type repeattr (* inlined *) = (
    krepeat (*tok*)
  * statementstr_ option
  * kuntil (*tok*)
  * expr
)

type try_ (* inlined *) = (
    ktry (*tok*)
  * statementstr_ option
  * anon_choice_kexc_opt_choice_stat__d8e7a89
  * kend (*tok*)
  * Token.t (* ";" *)
)

type trytr (* inlined *) = (
    ktry (*tok*)
  * statementstr_ option
  * anon_choice_kexc_opt_choice_stat__d8e7a89
  * kend (*tok*)
)

type varassigndef (* inlined *) = (
    kvar (*tok*)
  * identifier (*tok*)
  * (Token.t (* ":" *) * typeref) option
)

type while_ (* inlined *) = (kwhile (*tok*) * expr * kdo (*tok*) * statement)

type whiletr (* inlined *) = (
    kwhile (*tok*)
  * expr
  * kdo (*tok*)
  * statementtr option
)

type with_ (* inlined *) = (
    kwith (*tok*) * anon_opt_rep1_expr_COMMA_39d8f3f * expr * kdo (*tok*)
  * statement
)

type withtr (* inlined *) = (
    kwith (*tok*)
  * anon_opt_rep1_expr_COMMA_39d8f3f
  * expr
  * kdo (*tok*)
  * statementtr option
)

type exceptionhandlers (* inlined *) = (
    exceptionhandler list (* zero or more *)
  * anon_choice_exce_8373abe
  * exceptionelse option
)

type semgrep_expression (* inlined *) = (
    Token.t (* "__SEMGREP_EXPRESSION" *) * expr
)

type nestedif (* inlined *) = if_

type semgrep_statements (* inlined *) = (
    Token.t (* "__SEMGREP_STATEMENTS" *) * statementstr_
)

type semgrep_declarations (* inlined *) = (
    Token.t (* "__SEMGREP_DECLARATIONS" *)
  * [
        `Decl_c64a659 of decltype
      | `Decl_a20e53a of declvar
      | `Decl_d45e488 of declconst
      | `Decl_497d63e of declfield
      | `Decl_5f998b5 of declprop
      | `Decl_6ec32a9 of declproc
      | `Decl_8dd77dd of declprocfwd
      | `Declts of decltypes
      | `Declvs of declvars
      | `Declcs of declconsts
      | `Declus of decluses
      | `Semg_ellips of Token.t (* "..." *)
    ]
      list (* one or more *)
)

type exceptionelsetr (* inlined *) = (
    kelse (*tok*)
  * statement list (* zero or more *)
  * statementtr option
)

type statements_ (* inlined *) = statements

type extra = [
    `Space of Loc.t * space
  | `Comment of Loc.t * comment
  | `Ppdirective of Loc.t * ppdirective
]

type extras = extra list
